services:
  consumer:
    build: ./consumer
    container_name: consumer
    command: python receive.py
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  rabbitmq:
    build: ./exchange
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
