services:
  broker:
    container_name: rabbitmq
    build: ./broker
    ports:
      - 15671:15671
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - exchange
  producer:
    build: ./client
    command: python tasks.py
    depends_on:
      broker:
        condition: service_healthy
        restart: true
      parent:
        condition: service_started
      kid:
        condition: service_started
    environment:
      - RABBIT_HOST=amqps://broker:5671
    networks:
      - exchange
      - producer
  parent:
    build: ./client
    command: python parent.py
    scale: 2
    depends_on:
      broker:
        condition: service_healthy
        restart: true
    environment:
      - RABBIT_HOST=amqps://broker:5671
    networks:
      - exchange
      - consumer
  kid:
    build: ./client
    command: python kid.py
    scale: 2
    depends_on:
      broker:
        condition: service_healthy
        restart: true
    environment:
      - RABBIT_HOST=amqps://broker:5671
    networks:
      - exchange
      - consumer
networks:
  exchange:
  consumer:
  producer:
