services:
  consumer:
    build: ./consumer
    container_name: consumer
    command: python receive.py
    restart: always
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
