services:
  exchange:
    build: ./exchange
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - exchange
  consumer:
    build: ./consumer
    command: python receive.py
    depends_on:
      exchange:
        condition: service_healthy
        restart: true
    networks:
      - exchange
      - consumer
  producer:
    build: ./producer
    command: python send.py
    depends_on:
      exchange:
        condition: service_healthy
        restart: true
    networks:
      - exchange
      - producer
networks:
  exchange:
  consumer:
  producer:
