services:
  exchange:
    container_name: rabbitmq
    build: ./exchange
    ports:
      - 15671:15671
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - exchange
  producer:
    build: ./client
    command: python tasks.py
    depends_on:
      exchange:
        condition: service_healthy
        restart: true
    environment:
      - RABBIT_HOST=amqps://exchange:5671
    networks:
      - exchange
      - producer
  consumer:
    build: ./client
    command: python worker.py
    scale: 2
    depends_on:
      exchange:
        condition: service_healthy
        restart: true
    environment:
      - RABBIT_HOST=amqps://exchange:5671
    networks:
      - exchange
      - consumer
networks:
  exchange:
  consumer:
  producer:
