name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12" 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r producer/requirements.txt && pip install -r requirements_dev.txt
    - name: Typing
      run: mypy .
    - name: Security
      run: bandit -r .
    - name: Formatting
      run: black . -t py312 -l 120 --check
    - name: Imports
      run: isort . --check
    - name: Style
      run: flake8 .
